### ISSUE TITLE
Save Vec<f32>

### ISSUE THREAD

**Issue by antigol** [potocpav/npy-rs#3]
I dont manage to save a `Vec<f32>` with `to_file` because `NpyData` is not implemented for `f32`.

Is there a way to save a `Vec<f32>` such that when I load it from python it is a simple array of type `np.float32` ?

**Comment by potocpav** [comment]
Serializing a simple float is not implemented (not hard to do), just structs. But you can convert your `Vec<f32>` into a vector of structs that /derives the `NpyData` trait. For example (may not compile, I'm on mobile):

```#[derive(NpyData)]
struct Data {
    field: f32,
}
```
It is possible to unsafely transmute the `Vec<f32>` into `Vec<Data>` or just copy it over. Numpy will create a structured array from that, which can be converted to `np.float32` easily.

**Comment by potocpav** [comment]
Closing. If the suggested approach doesn't work, feel free to re-open the issue.
